(function attachVibeSwapSeedData(root, factory) {
  const catalog = factory();

  if (root) {
    root.vibeSwapSeedData = catalog;
  }

  if (typeof module !== "undefined" && module.exports) {
    module.exports = catalog;
  }
}(typeof globalThis !== "undefined" ? globalThis : null, function createVibeSwapSeedData() {
  return {
  foods: [
    {
      id: "salmon",
      name: "三文鱼",
      nameEn: "Salmon",
      aliases: ["大西洋鲑", "salmon"],
      category: "海鲜蛋白",
      image: "https://img.icons8.com/stickers/200/000000/salmon-sushi.png",
      texture: "丝滑",
      fatty: 9,
      umami: 8,
      acidity: 2,
      sweetness: 1,
      wateriness: 4,
      aroma: 6,
      cookMethods: ["生食", "炙烤", "拌饭"],
      dietaryTags: ["pescatarian"],
      allergens: ["fish"],
      bestFor: "寿司碗、轻食沙拉、拌饭和吐司",
      advantage: "口感高级、油脂饱满、鲜味稳定",
      disadvantage: "价格高、保鲜要求高",
      vibeNote: "适合提供顺滑油脂感和明显鲜味，是冷食里非常强势的主角食材。"
    },
    {
      id: "avocado",
      name: "牛油果",
      nameEn: "Avocado",
      aliases: ["鳄梨", "avocado"],
      category: "果脂类",
      image: "https://img.icons8.com/stickers/200/000000/avocado.png",
      texture: "绵密",
      fatty: 9,
      umami: 6,
      acidity: 1,
      sweetness: 1,
      wateriness: 5,
      aroma: 4,
      cookMethods: ["冷拌", "捣泥", "铺面"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "寿司碗、开放三明治、沙拉和酱泥",
      advantage: "容易买到，能补足丝滑感和油脂感",
      disadvantage: "海鲜鲜味弱，整体更偏植物清香",
      vibeNote: "很适合承担丝滑和丰润感，但无法完整复刻海产的咸鲜气质。"
    },
    {
      id: "egg",
      name: "鸡蛋",
      nameEn: "Egg",
      aliases: ["鸡子", "egg"],
      category: "日常蛋白",
      image: "https://img.icons8.com/stickers/200/000000/egg.png",
      texture: "软嫩",
      fatty: 5,
      umami: 6,
      acidity: 1,
      sweetness: 1,
      wateriness: 5,
      aroma: 4,
      cookMethods: ["水煮", "煎制", "炒制"],
      dietaryTags: ["vegetarian"],
      allergens: ["egg"],
      bestFor: "早餐碗、三明治、盖饭和简易沙拉",
      advantage: "便宜、常见、烹饪门槛低",
      disadvantage: "风味更温和，视觉冲击力不如生鲜蛋白",
      vibeNote: "鸡蛋在居家替代里非常实用，能提供柔软口感和一定鲜味，但风格更家常。"
    },
    {
      id: "tofu",
      name: "豆腐",
      nameEn: "Tofu",
      aliases: ["嫩豆腐", "tofu"],
      category: "植物蛋白",
      image: "https://img.icons8.com/stickers/200/000000/tofu.png",
      texture: "软嫩",
      fatty: 2,
      umami: 5,
      acidity: 1,
      sweetness: 1,
      wateriness: 7,
      aroma: 2,
      cookMethods: ["凉拌", "炖煮", "轻煎"],
      dietaryTags: ["vegan"],
      allergens: ["soy"],
      bestFor: "拌饭、味噌汤、清淡炒菜和轻食碗",
      advantage: "低脂、健康、价格友好，适合大多数家庭常备",
      disadvantage: "油脂感不足，需要额外调味或酱汁辅助",
      vibeNote: "豆腐很擅长接住清淡和软嫩的部分，但不适合直接替代高油脂食材的满足感。"
    },
    {
      id: "milk",
      name: "牛奶",
      nameEn: "Milk",
      aliases: ["全脂奶", "milk"],
      category: "乳制品",
      image: "https://img.icons8.com/stickers/200/000000/milk-bottle.png",
      texture: "顺滑",
      fatty: 6,
      umami: 3,
      acidity: 3,
      sweetness: 3,
      wateriness: 8,
      aroma: 3,
      cookMethods: ["冷饮", "加热", "打奶泡"],
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      bestFor: "拿铁、燕麦杯、奶油汤和基础烘焙",
      advantage: "适配范围广，是许多饮品和甜品的基础液体",
      disadvantage: "乳糖不耐受人群不友好",
      vibeNote: "牛奶偏中性、顺滑，适合作为液体基底。很多替代品都是在模仿它的顺口和乳感。"
    },
    {
      id: "yogurt",
      name: "酸奶",
      nameEn: "Yogurt",
      aliases: ["优格", "yogurt"],
      category: "乳制品",
      image: "https://img.icons8.com/stickers/200/000000/yogurt.png",
      texture: "浓稠",
      fatty: 5,
      umami: 2,
      acidity: 8,
      sweetness: 3,
      wateriness: 5,
      aroma: 4,
      cookMethods: ["冷拌", "杯装甜品", "调酱"],
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      bestFor: "冷饮、酱汁、隔夜燕麦和轻甜点",
      advantage: "浓稠度强，发酵感能让风味更立体",
      disadvantage: "酸度高，不适合所有咖啡和甜点场景",
      vibeNote: "酸奶比牛奶更有个性，适合替代质地，但会明显改变风味走向。"
    },
    {
      id: "chicken-breast",
      name: "鸡胸肉",
      nameEn: "Chicken Breast",
      aliases: ["鸡胸", "chicken breast"],
      category: "家常蛋白",
      image: "https://img.icons8.com/stickers/200/000000/chicken-breast.png",
      texture: "紧实",
      fatty: 2,
      umami: 7,
      acidity: 1,
      sweetness: 1,
      wateriness: 4,
      aroma: 4,
      cookMethods: ["水煮", "煎制", "焗烤"],
      dietaryTags: [],
      allergens: [],
      bestFor: "健身沙拉、热碗饭、卷饼和三明治",
      advantage: "高蛋白、低脂、好获取",
      disadvantage: "如果处理不好容易偏柴，顺滑感不强",
      vibeNote: "鸡胸肉胜在实用和稳定，更像是功能型替代，而不是气质完全复刻。"
    },
    {
      id: "beef",
      name: "牛肉",
      nameEn: "Beef",
      aliases: ["牛排肉", "beef"],
      category: "红肉蛋白",
      image: "https://img.icons8.com/stickers/200/000000/steak.png",
      texture: "紧实",
      fatty: 6,
      umami: 9,
      acidity: 1,
      sweetness: 1,
      wateriness: 3,
      aroma: 7,
      cookMethods: ["煎制", "炖煮", "热拌"],
      dietaryTags: [],
      allergens: [],
      bestFor: "能量碗、热拌饭、意面和煎炒主菜",
      advantage: "鲜味很强，饱腹感和存在感都足",
      disadvantage: "价格偏高，整体调性更厚重",
      vibeNote: "牛肉在鲜味维度很强，适合作为强风味替代，但会把菜整体拉向更浓郁的方向。"
    },
    {
      id: "tuna",
      name: "金枪鱼",
      nameEn: "Tuna",
      aliases: ["吞拿鱼", "tuna"],
      category: "海鲜蛋白",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Tuna",
      texture: "紧实",
      fatty: 4,
      umami: 8,
      acidity: 1,
      sweetness: 1,
      wateriness: 4,
      aroma: 6,
      cookMethods: ["生食", "炙烤", "拌饭"],
      dietaryTags: ["pescatarian"],
      allergens: ["fish"],
      bestFor: "寿司碗、三明治夹馅、沙拉和蛋白碗",
      advantage: "鲜味强、蛋白高，很多冷食里都好替换",
      disadvantage: "油脂感不如三文鱼，口感更紧实",
      vibeNote: "金枪鱼更偏干净和利落，适合替代海鲜主角位，但整体风格更清爽。"
    },
    {
      id: "shrimp",
      name: "虾仁",
      nameEn: "Shrimp",
      aliases: ["虾", "shrimp"],
      category: "海鲜蛋白",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Shrimp",
      texture: "弹嫩",
      fatty: 2,
      umami: 7,
      acidity: 1,
      sweetness: 2,
      wateriness: 5,
      aroma: 5,
      cookMethods: ["水煮", "快炒", "拌饭"],
      dietaryTags: ["pescatarian"],
      allergens: ["shellfish"],
      bestFor: "轻食碗、意面、炒饭和快手沙拉",
      advantage: "熟制快、鲜味稳定、存在感明显",
      disadvantage: "油脂感弱，冷食时不够丝滑",
      vibeNote: "虾仁像一个更轻盈的海鲜替身，适合保住鲜味但不适合复刻油润感。"
    },
    {
      id: "pork",
      name: "猪肉",
      nameEn: "Pork",
      aliases: ["里脊", "pork"],
      category: "家常蛋白",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Pork",
      texture: "紧实",
      fatty: 5,
      umami: 7,
      acidity: 1,
      sweetness: 1,
      wateriness: 4,
      aroma: 5,
      cookMethods: ["煎制", "快炒", "炖煮"],
      dietaryTags: [],
      allergens: [],
      bestFor: "家常炒菜、盖饭、三明治和热食碗",
      advantage: "家用普适性高，兼顾鲜味和油脂",
      disadvantage: "风格偏厚重，不适合所有清爽场景",
      vibeNote: "猪肉比鸡胸更圆润，适合补足一点脂香，但整体气质会更家常。"
    },
    {
      id: "tempeh",
      name: "天贝",
      nameEn: "Tempeh",
      aliases: ["印尼天贝", "tempeh"],
      category: "植物蛋白",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Tempeh",
      texture: "紧实",
      fatty: 4,
      umami: 6,
      acidity: 1,
      sweetness: 1,
      wateriness: 3,
      aroma: 5,
      cookMethods: ["煎制", "焗烤", "拌饭"],
      dietaryTags: ["vegan"],
      allergens: ["soy"],
      bestFor: "植物蛋白碗、卷饼、沙拉和热三明治",
      advantage: "蛋白密度高，咬感更接近肉类",
      disadvantage: "豆发酵风味明显，不一定适合所有人",
      vibeNote: "天贝比豆腐更像肉类替代，特别适合需要紧实口感的场景。"
    },
    {
      id: "chickpeas",
      name: "鹰嘴豆",
      nameEn: "Chickpeas",
      aliases: ["鸡豆", "chickpeas"],
      category: "植物蛋白",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Chickpeas",
      texture: "绵实",
      fatty: 2,
      umami: 4,
      acidity: 1,
      sweetness: 2,
      wateriness: 3,
      aroma: 3,
      cookMethods: ["炖煮", "烘烤", "捣泥"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "沙拉、豆泥酱、烤碗和植物蛋白拼盘",
      advantage: "便于储存，饱腹感强，适合做豆泥和烤豆",
      disadvantage: "鲜味和油脂感都偏弱，需要调味支持",
      vibeNote: "鹰嘴豆更像是温和稳妥的结构型替代，适合撑起体积和绵密感。"
    },
    {
      id: "oat-milk",
      name: "燕麦奶",
      nameEn: "Oat Milk",
      aliases: ["燕麦饮", "oat milk"],
      category: "植物奶",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Oat+Milk",
      texture: "顺滑",
      fatty: 4,
      umami: 1,
      acidity: 2,
      sweetness: 4,
      wateriness: 8,
      aroma: 3,
      cookMethods: ["冷饮", "加热", "打奶泡"],
      dietaryTags: ["vegan"],
      allergens: ["gluten"],
      bestFor: "拿铁、谷物碗、奶昔和轻烘焙",
      advantage: "植物感柔和，和咖啡搭配接受度高",
      disadvantage: "乳感和鲜味不如牛奶，容易略甜",
      vibeNote: "燕麦奶是很实用的牛奶替代，核心优势是顺滑度和易搭配性。"
    },
    {
      id: "coconut-milk",
      name: "椰奶",
      nameEn: "Coconut Milk",
      aliases: ["椰浆", "coconut milk"],
      category: "植物奶",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Coconut+Milk",
      texture: "浓滑",
      fatty: 8,
      umami: 2,
      acidity: 1,
      sweetness: 3,
      wateriness: 6,
      aroma: 6,
      cookMethods: ["炖煮", "调饮", "烘焙"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "咖喱、热带风味甜品、奶昔和浓汤",
      advantage: "油脂感足，能快速补出奶香和厚度",
      disadvantage: "椰香明显，会强烈改变风味方向",
      vibeNote: "椰奶擅长补足浓润感，但会把菜整体拉向热带和甜香方向。"
    },
    {
      id: "cream",
      name: "淡奶油",
      nameEn: "Cream",
      aliases: ["稀奶油", "cream"],
      category: "乳制品",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Cream",
      texture: "浓滑",
      fatty: 9,
      umami: 2,
      acidity: 2,
      sweetness: 2,
      wateriness: 4,
      aroma: 3,
      cookMethods: ["打发", "炖煮", "烘焙"],
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      bestFor: "意面酱、奶油汤、蛋糕和甜品夹层",
      advantage: "厚度和顺滑度很强，能快速建立浓郁口感",
      disadvantage: "热量高，日常替代成本偏重",
      vibeNote: "淡奶油像是把乳感推到更厚重的一端，适合做口感加强型替代。"
    },
    {
      id: "butter",
      name: "黄油",
      nameEn: "Butter",
      aliases: ["奶油块", "butter"],
      category: "乳制品",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Butter",
      texture: "油润",
      fatty: 10,
      umami: 2,
      acidity: 1,
      sweetness: 1,
      wateriness: 1,
      aroma: 5,
      cookMethods: ["烘焙", "煎制", "抹面"],
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      bestFor: "烘焙、煎香、做酱和抹面提香",
      advantage: "脂香强，少量就能显著提升满足感",
      disadvantage: "液体替代能力差，风格很重",
      vibeNote: "黄油更像是油脂和香气补强器，不是所有奶类都能直接用它顶。"
    },
    {
      id: "mozzarella",
      name: "马苏里拉",
      nameEn: "Mozzarella",
      aliases: ["mozzarella", "马苏"],
      category: "乳制品",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Mozzarella",
      texture: "拉丝",
      fatty: 7,
      umami: 5,
      acidity: 2,
      sweetness: 1,
      wateriness: 4,
      aroma: 4,
      cookMethods: ["焗烤", "冷拌", "夹馅"],
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      bestFor: "披萨、烤吐司、焗饭和卡普雷塞沙拉",
      advantage: "拉丝表现强，视觉效果好",
      disadvantage: "风味比较温和，不是浓郁型奶酪",
      vibeNote: "马苏里拉更像结构和拉丝担当，适合视觉和口感迁移。"
    },
    {
      id: "cream-cheese",
      name: "奶油奶酪",
      nameEn: "Cream Cheese",
      aliases: ["cream cheese", "软奶酪"],
      category: "乳制品",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Cream+Cheese",
      texture: "厚滑",
      fatty: 8,
      umami: 3,
      acidity: 3,
      sweetness: 2,
      wateriness: 3,
      aroma: 4,
      cookMethods: ["抹面", "烘焙", "调酱"],
      dietaryTags: ["vegetarian"],
      allergens: ["milk"],
      bestFor: "贝果、芝士蛋糕、奶酪酱和夹馅",
      advantage: "质地稳定，抹面和夹层表现很好",
      disadvantage: "风格偏厚，不适合替代轻盈乳品",
      vibeNote: "奶油奶酪是更厚、更稳的乳感版本，适合需要稠度和附着力的场景。"
    },
    {
      id: "mushroom",
      name: "蘑菇",
      nameEn: "Mushroom",
      aliases: ["菌菇", "mushroom"],
      category: "鲜蔬菌菇",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Mushroom",
      texture: "柔嫩",
      fatty: 1,
      umami: 8,
      acidity: 1,
      sweetness: 1,
      wateriness: 5,
      aroma: 6,
      cookMethods: ["煎制", "炖煮", "快炒"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "意面、炖饭、汉堡和植物系主菜",
      advantage: "鲜味很强，是很多肉类替代里的核心角色",
      disadvantage: "缺少真正的油脂感，口感也更轻",
      vibeNote: "蘑菇是鲜味迁移的明星选手，特别适合补足肉类缺位时的气场。"
    },
    {
      id: "tomato",
      name: "番茄",
      nameEn: "Tomato",
      aliases: ["西红柿", "tomato"],
      category: "鲜蔬果",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Tomato",
      texture: "多汁",
      fatty: 1,
      umami: 4,
      acidity: 7,
      sweetness: 3,
      wateriness: 9,
      aroma: 4,
      cookMethods: ["凉拌", "炖煮", "烘烤"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "意面酱、沙拉、炖菜和烤盘料理",
      advantage: "酸甜平衡好，含水量高，适合带出清爽感",
      disadvantage: "本体感偏轻，不适合顶替厚重食材",
      vibeNote: "番茄擅长补酸度和汁感，是很多料理里风味平衡器而不是主体油脂源。"
    },
    {
      id: "cucumber",
      name: "黄瓜",
      nameEn: "Cucumber",
      aliases: ["青瓜", "cucumber"],
      category: "鲜蔬果",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Cucumber",
      texture: "脆爽",
      fatty: 0,
      umami: 1,
      acidity: 1,
      sweetness: 1,
      wateriness: 10,
      aroma: 2,
      cookMethods: ["生食", "凉拌", "夹馅"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "三明治、卷饼、冷盘和清爽沙拉",
      advantage: "清爽、便宜、含水量高，适合补脆感",
      disadvantage: "风味和厚度都弱，不能承担主角食材功能",
      vibeNote: "黄瓜更像质地和清爽度替代，不适合承担浓郁型食材的角色。"
    },
    {
      id: "cauliflower",
      name: "花椰菜",
      nameEn: "Cauliflower",
      aliases: ["菜花", "cauliflower"],
      category: "鲜蔬果",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Cauliflower",
      texture: "松散",
      fatty: 0,
      umami: 3,
      acidity: 1,
      sweetness: 2,
      wateriness: 4,
      aroma: 2,
      cookMethods: ["烘烤", "快炒", "打碎"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "低碳米饭替代、烤盘菜和浓汤",
      advantage: "吸味能力好，适合做结构型主食替代",
      disadvantage: "自身风味轻，饱腹感和主食感有限",
      vibeNote: "花椰菜常用来顶主食或做绵松底层，更像结构迁移而不是风味迁移。"
    },
    {
      id: "spinach",
      name: "菠菜",
      nameEn: "Spinach",
      aliases: ["波菜", "spinach"],
      category: "鲜蔬果",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Spinach",
      texture: "柔软",
      fatty: 0,
      umami: 3,
      acidity: 1,
      sweetness: 1,
      wateriness: 7,
      aroma: 3,
      cookMethods: ["快炒", "汆烫", "拌面"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "蛋饼、意面、轻汤和早餐碗",
      advantage: "颜色和柔软叶感都适合补绿色蔬菜位",
      disadvantage: "体积塌缩明显，存在感偏弱",
      vibeNote: "菠菜偏柔和，适合用来接住绿叶菜角色，但不适合做质地主角。"
    },
    {
      id: "zucchini",
      name: "西葫芦",
      nameEn: "Zucchini",
      aliases: ["夏南瓜", "zucchini"],
      category: "鲜蔬果",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Zucchini",
      texture: "柔嫩",
      fatty: 0,
      umami: 2,
      acidity: 1,
      sweetness: 2,
      wateriness: 8,
      aroma: 2,
      cookMethods: ["煎制", "烘烤", "拌面"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "烤盘菜、意面、轻煎配菜和低碳料理",
      advantage: "容易吸味，熟后质地柔软",
      disadvantage: "本身风味弱，容易出水",
      vibeNote: "西葫芦适合承担轻盈蔬菜位，能补柔软感但不适合浓味主菜替代。"
    },
    {
      id: "potato",
      name: "土豆",
      nameEn: "Potato",
      aliases: ["马铃薯", "potato"],
      category: "根茎主食",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Potato",
      texture: "绵密",
      fatty: 0,
      umami: 2,
      acidity: 1,
      sweetness: 1,
      wateriness: 3,
      aroma: 2,
      cookMethods: ["烘烤", "水煮", "压泥"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "泥、薯块、浓汤和焗烤配菜",
      advantage: "饱腹感强，绵密度高，适合补体积",
      disadvantage: "风味比较平，不提供鲜味和油脂",
      vibeNote: "土豆是非常强的结构型替代，擅长给菜增加厚实感和绵密感。"
    },
    {
      id: "banana",
      name: "香蕉",
      nameEn: "Banana",
      aliases: ["banana", "蕉"],
      category: "鲜蔬果",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Banana",
      texture: "绵密",
      fatty: 1,
      umami: 1,
      acidity: 2,
      sweetness: 8,
      wateriness: 5,
      aroma: 6,
      cookMethods: ["打泥", "烘焙", "调饮"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "奶昔、燕麦碗、松饼和健康烘焙",
      advantage: "天然甜度高，能补黏合感和绵密口感",
      disadvantage: "香蕉香气明显，不适合所有甜品替代",
      vibeNote: "香蕉在甜口替代里很强，尤其适合接住绵密感和天然甜味。"
    },
    {
      id: "rice",
      name: "米饭",
      nameEn: "Rice",
      aliases: ["白饭", "rice"],
      category: "主食谷物",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Rice",
      texture: "软弹",
      fatty: 0,
      umami: 1,
      acidity: 0,
      sweetness: 1,
      wateriness: 4,
      aroma: 1,
      cookMethods: ["蒸煮", "拌饭", "焗饭"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "饭碗、咖喱饭、炒饭和寿司饭底",
      advantage: "中性稳定，是最通用的主食底座之一",
      disadvantage: "本身风味弱，需要靠配料和酱汁撑气质",
      vibeNote: "米饭像一个中性底板，自己不抢戏，但能托住很多替代组合。"
    },
    {
      id: "pasta",
      name: "意面",
      nameEn: "Pasta",
      aliases: ["pasta", "面条"],
      category: "主食谷物",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Pasta",
      texture: "弹韧",
      fatty: 1,
      umami: 1,
      acidity: 0,
      sweetness: 1,
      wateriness: 3,
      aroma: 1,
      cookMethods: ["水煮", "拌酱", "焗烤"],
      dietaryTags: ["vegan"],
      allergens: ["gluten"],
      bestFor: "奶油面、番茄面、焗面和冷面沙拉",
      advantage: "酱汁承载能力强，口感稳定",
      disadvantage: "风味中性，无法替代米饭那种颗粒分明感",
      vibeNote: "意面更重视弹韧和挂汁能力，适合作为酱汁型主食底。"
    },
    {
      id: "bread",
      name: "面包",
      nameEn: "Bread",
      aliases: ["吐司", "bread"],
      category: "主食谷物",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Bread",
      texture: "蓬松",
      fatty: 2,
      umami: 2,
      acidity: 1,
      sweetness: 2,
      wateriness: 2,
      aroma: 4,
      cookMethods: ["夹馅", "烘烤", "抹酱"],
      dietaryTags: ["vegan"],
      allergens: ["gluten"],
      bestFor: "三明治、吐司盘、开放面包和法式早餐",
      advantage: "上手快，适合承载酱料和主料",
      disadvantage: "含水量低，不适合替代湿润型主食",
      vibeNote: "面包更像一个蓬松载体，擅长接住夹馅和抹酱场景。"
    },
    {
      id: "oats",
      name: "燕麦",
      nameEn: "Oats",
      aliases: ["麦片", "oats"],
      category: "主食谷物",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Oats",
      texture: "糊化",
      fatty: 3,
      umami: 1,
      acidity: 1,
      sweetness: 2,
      wateriness: 4,
      aroma: 3,
      cookMethods: ["熬煮", "冷泡", "烘焙"],
      dietaryTags: ["vegan"],
      allergens: ["gluten"],
      bestFor: "早餐碗、隔夜燕麦、能量棒和健康烘焙",
      advantage: "饱腹感好，和奶类与水果兼容性高",
      disadvantage: "颗粒感和面粉结构不能完全互替",
      vibeNote: "燕麦偏温和和健康路线，适合早餐和轻烘焙里的基础替代。"
    },
    {
      id: "flour",
      name: "面粉",
      nameEn: "Flour",
      aliases: ["小麦粉", "flour"],
      category: "烘焙原料",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Flour",
      texture: "粉质",
      fatty: 1,
      umami: 1,
      acidity: 0,
      sweetness: 1,
      wateriness: 0,
      aroma: 1,
      cookMethods: ["烘焙", "裹粉", "勾芡"],
      dietaryTags: ["vegan"],
      allergens: ["gluten"],
      bestFor: "蛋糕、饼干、面糊和基础面团",
      advantage: "用途广，是烘焙和勾芡的基础骨架",
      disadvantage: "结构性强，但风味信息很少",
      vibeNote: "面粉不是风味型材料，更像是结构框架，很多替代都在和它的成型能力竞争。"
    },
    {
      id: "soy-sauce",
      name: "酱油",
      nameEn: "Soy Sauce",
      aliases: ["生抽", "soy sauce"],
      category: "酱料调味",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Soy+Sauce",
      texture: "液体",
      fatty: 0,
      umami: 9,
      acidity: 1,
      sweetness: 1,
      wateriness: 9,
      aroma: 5,
      cookMethods: ["蘸食", "炖煮", "拌饭"],
      dietaryTags: ["vegan"],
      allergens: ["soy", "gluten"],
      bestFor: "日式饭碗、蘸汁、炒菜和酱汁打底",
      advantage: "鲜味强，少量就能显著补味",
      disadvantage: "咸度高，不提供油脂和厚度",
      vibeNote: "酱油是鲜味和咸香的捷径，适合补风味，不适合补质地。"
    },
    {
      id: "miso",
      name: "味噌",
      nameEn: "Miso",
      aliases: ["miso", "味增"],
      category: "酱料调味",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Miso",
      texture: "厚糊",
      fatty: 2,
      umami: 9,
      acidity: 2,
      sweetness: 2,
      wateriness: 3,
      aroma: 6,
      cookMethods: ["煮汤", "腌制", "调酱"],
      dietaryTags: ["vegan"],
      allergens: ["soy"],
      bestFor: "味噌汤、酱烤、蘸酱和咸口调味底",
      advantage: "发酵鲜味强，稠度比酱油更能挂味",
      disadvantage: "风格明显，不适合所有西式场景",
      vibeNote: "味噌是更厚、更发酵感的鲜味来源，适合做咸口风味加强型替代。"
    },
    {
      id: "mayonnaise",
      name: "蛋黄酱",
      nameEn: "Mayonnaise",
      aliases: ["美乃滋", "mayonnaise"],
      category: "酱料调味",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Mayo",
      texture: "浓滑",
      fatty: 9,
      umami: 3,
      acidity: 6,
      sweetness: 2,
      wateriness: 2,
      aroma: 3,
      cookMethods: ["抹酱", "拌沙拉", "调味"],
      dietaryTags: ["vegetarian"],
      allergens: ["egg"],
      bestFor: "三明治、沙拉、蘸酱和日式小食",
      advantage: "既补油脂又补酸感，做冷食很高效",
      disadvantage: "风味方向固定，热应用场景有限",
      vibeNote: "蛋黄酱是冷食里很强的质地修复器，尤其适合补浓滑和酸感。"
    },
    {
      id: "olive-oil",
      name: "橄榄油",
      nameEn: "Olive Oil",
      aliases: ["olive oil", "食用橄榄油"],
      category: "酱料调味",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Olive+Oil",
      texture: "油润",
      fatty: 10,
      umami: 0,
      acidity: 1,
      sweetness: 0,
      wateriness: 0,
      aroma: 4,
      cookMethods: ["凉拌", "煎制", "收尾"],
      dietaryTags: ["vegan"],
      allergens: [],
      bestFor: "沙拉、烤菜、意面和蘸面包",
      advantage: "补油脂效率高，适合把轻食拉得更润",
      disadvantage: "单独使用时风味层次有限",
      vibeNote: "橄榄油更像油脂度补偿工具，适合给原本偏干的替代品加回顺滑感。"
    },
    {
      id: "peanut-butter",
      name: "花生酱",
      nameEn: "Peanut Butter",
      aliases: ["peanut butter", "花生抹酱"],
      category: "酱料调味",
      image: "https://placehold.co/200x200/F6EFE3/243127?text=Peanut+Butter",
      texture: "厚糊",
      fatty: 9,
      umami: 2,
      acidity: 1,
      sweetness: 3,
      wateriness: 1,
      aroma: 7,
      cookMethods: ["抹面", "调酱", "烘焙"],
      dietaryTags: ["vegan"],
      allergens: ["peanut"],
      bestFor: "吐司、能量杯、东南亚风味酱汁和曲奇",
      advantage: "香气和厚度都强，少量即可显著提升满足感",
      disadvantage: "花生风味太明显，不适合中性替代",
      vibeNote: "花生酱擅长做高存在感替代，特别适合厚重、香气型场景。"
    }
  ],
  dimensions: [
    { key: "fatty", label: "油脂感", weight: 1.4 },
    { key: "umami", label: "鲜味", weight: 1.6 },
    { key: "acidity", label: "酸度", weight: 0.8 },
    { key: "sweetness", label: "甜感", weight: 0.5 },
    { key: "wateriness", label: "含水量", weight: 0.7 },
    { key: "aroma", label: "香气强度", weight: 0.9 }
  ]
  };
}));
